"""first migration

Revision ID: ce9f31524f7b
Revises: 
Create Date: 2024-11-12 21:29:29.730095

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'ce9f31524f7b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
